<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use DateTime;
use DateInterval;

/**
 * IpnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpnRepository extends EntityRepository
{
	public function getSample($dateBefore,$dateAfter){
		$qb = $this->createQueryBuilder('ipn');
		$qb->where('ipn.vadsTransUuid != :identifier')->setParameter('identifier','')->andWhere('ipn.vadsCtxMode = :type')->setParameter('type','PRODUCTION')->andWhere('ipn.vadsEffectiveCreationDate > :datebefore')->setParameter('datebefore',$dateBefore)->andWhere('ipn.vadsEffectiveCreationDate < :dateAfter')->setParameter('dateAfter',$dateAfter)->orderBy('ipn.vadsEffectiveCreationDate','DESC')->groupBy('ipn.vadsTransUuid')->setMaxResults(
			20);
		return $qb->getQuery()->getResult();
	}

	public function findAllIpn($dates){
		$qb = $this->createQueryBuilder('ipn');
		return $qb->where("ipn.vadsCtxMode = 'PRODUCTION'")->orderBy('ipn.vadsEffectiveCreationDate','DESC')->andWhere('ipn.vadsEffectiveCreationDate > ?1')->andWhere('ipn.vadsEffectiveCreationDate < ?2')->setParameters(array(1=>$dates['dateBefore'],2=>$dates['dateAfter']))->getQuery()->getResult();
	}

	public function getLast($limit,$dates){
		$query = $this->getEntityManager()->createQuery("SELECT ipn.vadsTransUuid, ipn.vadsSiteId FROM AppBundle:Ipn ipn WHERE ipn.vadsCtxMode = 'PRODUCTION' AND ipn.vadsEffectiveCreationDate > ?1 AND ipn.vadsEffectiveCreationDate < ?2 AND ipn.vadsTransUuid NOT IN (SELECT payment.uuid FROM AppBundle:Payment payment) ORDER BY ipn.vadsEffectiveCreationDate DESC")->setMaxResults($limit)->setParameters(array(1=>$dates['dateBefore'],2=>$dates['dateAfter']));
		return $query->getResult();
	}

	public function getLastDate(){
		$qb = $this->createQueryBuilder('ipn');
		return $qb->select('MAX(ipn.ts)')->getQuery()->getSingleScalarResult();
	}

	public function countDayIpn($dates){
		$query = $this->getEntityManager()->createQuery("SELECT COUNT(DISTINCT ipn.vadsTransUuid) FROM AppBundle:Ipn ipn WHERE ipn.vadsEffectiveCreationDate > ?1 AND ipn.vadsEffectiveCreationDate < ?2 AND ipn.vadsCtxMode = 'PRODUCTION' AND ipn.vadsTransUuid NOT IN (SELECT payment.uuid FROM AppBundle:Payment payment) ORDER BY ipn.vadsEffectiveCreationDate DESC")->setParameters(array(1=>$dates['dateBefore'],2=>$dates['dateAfter']));
		return $query->getSingleScalarResult();
	}
}
