fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
login:
    pattern:   /login
    defaults:  { _controller: UserBundle:Security:login }
app:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix: /
default_route:
    pattern: /{url}
    defaults: { _controller: AppBundle:Main:create, url: "ipn" }
    requirements:
        url: "/ipn.+"
payments:
  type: rest
  resource: CoreBundle\Controller\PaymentsController
