# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
# parameters:
#    parameter_name: value

services:
    app.Tool:
        class: AppBundle\Tools\Tool
    app.Config:
        class: AppBundle\PayzenWSv5\Config
        arguments: [@Request_stack]
    app.PayzenWSv5:
        class: AppBundle\PayzenWSv5\PayzenWSv5
        arguments: [@app.Config]
    app.Loader:
        class: AppBundle\PayzenWSv5\Loader
        arguments: [@doctrine.orm.entity_manager,@app.PayzenWSv5]
    app.twig.extension.TwigAddOn:
        class: AppBundle\Tools\TwigAddOn
        arguments: [@security.context]
        tags:
            - { name: twig.extension}
